name: Daily Action-Demo

on:
    push:


jobs:
    Daily-Save:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Run Save
              run: python files.py
